# Lista 1 - Sheldon Ross

##Capítulo 3

Questões extras*: 3, 4, 5, 6, 7.

### Questão 3*

$$\int_{0}^{1}exp\{e^x\}dx$$

In [ ]:
n=10000
x3 = runif(n,0,1)
q3 = mean(exp(exp(x3)));q3
# valor real = 6.31656 (WolframAlpha)

[1] 6.341524

###Questão 4*


 $$\int_{0}^{1}(1-x^2)^{3/2}dx$$

In [ ]:
n=10000
x4 = runif(n,0,1)
q4 = mean((1-(x4)^2)^(3/2));q4
# valor real = 0.589049 (WolframAlpha)

[1] 0.5874268

###Questão 5*

$$\int_{-2}^{2}e^{x+x^2}dx$$

In [ ]:
n=10000
x5 = runif(n,-2,2)
q5 = mean(exp(x5+x5^2)*4);q5 #tem que multiplicar por 4 pq é o comprimento do intervalo, se fosse de -3 até 3 teria que multiplicar por 6
# valor real = 93.1628 (WolframAlpha)

[1] 93.64861

### Questão 6*

$$\int_{0}^{\infty} x(1+x^2)^{-2} $$

In [ ]:
n=10000
x = rexp(n,1)
f = function(x){x*((1+x^2)^-2)}
q6 = mean(f(x));q6
# valor real = 0.5 (WolframAlpha)

[1] 0.1867719

### Questão 7*

$$\int_{-\infty}^{\infty}e^{-x^2} $$

In [ ]:
n=10000
x = rexp(n,1)
f = function(x){exp(-x^2)}
q7 = 2*mean(f(x));q7
# valor real = 1.77245 (WolframAlpha)

[1] 1.093851

### Questão 8

$$ \int_{0}^{1}\int_{0}^{1}{e^{(x+y)^2}}dydx $$

In [ ]:
set.seed(43)

# definindo um tamanho de amostra grande padrão
n = 10000

# definindo amostras U[0,1] das variáveis
x = runif(n, 0, 1)
y = runif(n, 0, 1)

# função a integrar
f = function(x, y){exp((x+y)^2)}

# valor esperado
esp = mean(f(x,y))

# aproximando a integral
esp * (1-0)*(1-0)

# valor real = 4,89916 (verificado via WolframAlpha)

[1] 4.89061

### Questão 9

$$ \int_{0}^{∞}\int_{0}^{x}{e^{-(x+y)}}dydx $$

In [ ]:
set.seed(43)

# gerando amostras das variáveis
x = rexp(n,1)
y = runif(n,0,x)

# função a integrar
f = function(x, y){exp(-(x+y))}

# valor esperado
esp = mean(f(x,y))

# aproximando a integral
esp

# valor real = 0.5 (verificado via WolframAlpha)

[1] 0.4060052

### Questão 10

Calcular, por simulação:

$$ Cov(U, e^U),\; U \sim U(0,1)$$

Para lembrar:

$$ Cov(X,Y) = E[XY] - E[X]E[Y]$$

In [ ]:
set.seed(43)

# gerando amostra uniforme
U = runif(n)

# função
f = exp(U)

# calculando as esperanças
esp1 = mean(U*f)
esp2 = mean(U) * mean(f)

# covariância
esp1 - esp2

# com um tamanho de amostra maior:


[1] 0.1406043

### Questão 12

$$ N = \min \left\{n: \sum_{i=1}^{n}{U_{i}} > 1 \right\}, U_{i} \sim U(0,1) $$

In [ ]:
set.seed(43)

# função para calcular N
minimo = function(){
  N = 0
  soma = 0

  while(soma <= 1) {
    N = N + 1
    soma = soma + runif(1)
  }
  return(N)
}

a = replicate(100, minimo())
b = replicate(1000, minimo())
c = replicate(10000, minimo())

cat("100 repetições:", mean(a), "\n\n")
cat("1000 repetições:", mean(b), "\n\n")
cat("10000 repetições:", mean(c), "\n")

# o valor parece convergir para algo em torno de 2.7 ou 2.71
# quanto mais iterações, mais próximo fica de uma exponencial (e^{1})

100 repetições: 2.68 

1000 repetições: 2.755 

10000 repetições: 2.7226 


### Questão 13

$$ N = \max \left\{ \prod_{i=1}^{n}{U_{i} \geq e^{-3}} \right\}, U_{i} \sim U(0,1) $$

Para lembrar:

$$ -\log {U} \sim Exp(1)$$

In [ ]:
set.seed(43)

### item a) ###

# função para calcular N
maximo = function() {
  N = 0
  prod = 1

  while(prod >= exp(-3)) {
    N = N + 1
    prod = prod * runif(1)
  }
  return(N)
}

cat("E[N]=", mean(replicate(10000, maximo())), "\n\n")
# o valor parece convergir para 4, quanto mais iterações houver


### item b) ###
valores_N = replicate(10000, maximo())

# a média é um bom estimador
for(i in 1:6){
  cat("Prob. N =", i, ":", mean(valores_N == i), "\n\n")
}

E[N]= 3.9763 

Prob. N = 1 : 0.0505 

Prob. N = 2 : 0.1597 

Prob. N = 3 : 0.227 

Prob. N = 4 : 0.218 

Prob. N = 5 : 0.1666 

Prob. N = 6 : 0.0982 



##Capítulo 4


Questões extras*: 12.

###Questão 4

In [ ]:
set.seed(19)
n = 10000
acertos = c()
for (i in 1:n) {
  carta <- sample(1:100, 100)
  acertos[i] <- sum(carta == 1:100) #soma o num. de acertos
}
media = mean(acertos);media
variancia = var(acertos); variancia

#prob. sucesso = 1/100;
#E(prob. sucesso) = E(1/100) + E(1/100) + ... + E(1/100) (100 vezes)
#então, E(prob. sucesso) = 1

#var(prob. sucesso) = (1/100 * 1-1/100) * 100 = 0.99


[1] 1.0038

[1] 0.9810837

###Questão 7

In [ ]:
set.seed(19)
f = function() {
  lancamentos <- rowSums(replicate(2, sample(6, 5000, replace=TRUE))) #soma as duas colunas de tamanho 5k
  for(i in 1:5000){
    if(length(unique(lancamentos[1:i])) == 11) break;
  } #de i em 1 até 5k se o tamanho de cada lançamento unico for = 11 acaba a contagem
  return(i) #e retorna o valor de i
}
res = replicate(5000, f()) #replica 5k vezes a simulacao
mean(res) #valor esperado de lançamentos

[1] 61.2602

### Questão 12*

Mostre que $$E[|Z|] = \bigg(\frac{2}{\pi}\bigg)^{1/2} \approx 0,798 $$

In [ ]:
set.seed(19)
z=rnorm(10000)
z_abs=abs(z)
media=mean(z_abs);media #Z estimado

z_t=(2/pi)^0.5;z_t #Z teórico

[1] 0.7920935

[1] 0.7978846

### Questão 17

In [ ]:
# função base
probabilidade = function(j) {
  return(0.5^(j+1) + (0.5*2^(j-1))/(3^j))
}

# função de geração de X
gerar_valores <- function(n) {
  X = 1:n
  probabilidades = sapply(X, probabilidade)
  probabilidades = probabilidades / sum(probabilidades)
  amostra = sample(X, size = n, replace = TRUE, prob = probabilidades)
  return(amostra)
}

# gerando X
valores = gerar_valores(5)
print(valores)
print(probabilidade(valores))

[1] 1 3 2 5 5
[1] 0.41666667 0.13657407 0.23611111 0.04854681 0.04854681


# Lista 2

### Questão 1

 Vetor escore com função de ligação logito



In [ ]:
#Questão 1
n = 15
x = 1:10
w = c(2,4,3,6,5,2,1,9,6,4)

vs = function(a,b){
  esc.1 = sum(-2*n*exp(a+b*x)*((w-n)*exp(a+b*x)+w)/(exp(a+b*x)+1)^3)
  esc.2 = sum(-2*n*x*((exp(a)*w-exp(a)*n)*exp(x*b)+w)*exp(x*b+a)/(exp(x*b+a)+1)^3)
  return(c(esc.1,esc.2))
}

#teste
vs(1,10); vs(2,12); vs(-1,-10); vs(4,3)

[1] 0.006513570 0.006513821

[1] 0.0003242970 0.0003242987

[1] -0.001002034 -0.001002125

[1] 0.3704387 0.3871442

### Questão 2

Matriz hessiana com função de ligação logito

In [ ]:
#Questão 2
H = function(a,b){
  hab = sum(2*n*x*exp(x*b+a)*(2*n*exp(x*b+a)+(exp(2*a)*w-exp(2*a)*n)*exp(2*x*b)-w)/(exp(x*b+a)+1)^4)
  ha.2 = sum(2*n*exp(a+b*x)*((w-n)*exp(2*a+2*b*x)+2*n*exp(a+b*x)-w)/(exp(a+b*x)+1)^4)
  hb.2 = sum(2*n*x^2*exp(x*b+a)*(2*n*exp(x*b+a)+(exp(2*a)*w-exp(2*a)*n)*exp(2*x*b)-w)/(exp(x*b+a)+1)^4)
  h = matrix(c(ha.2,hab,hab,hb.2),2,2)
  return(h)
}

H(1,10); H(2,12); H(-1,-10); H(4,3)

[,1]         [,2]        
[1,] -0.006513227 -0.006513478
[2,] -0.006513478 -0.006513978

[,1]          [,2]         
[1,] -0.0003242962 -0.0003242979
[2,] -0.0003242979 -0.0003243012

[,1]         [,2]        
[1,] -0.001001875 -0.001001966
[2,] -0.001001966 -0.001002148

[,1]       [,2]      
[1,] -0.3694174 -0.3861207
[2,] -0.3861207 -0.4213595

# Lista 3

### Questão 1

Considere que temos interesse em estudar a relação entre peso e altura via simulação. Portanto, inicialmente gere amostra aleatória de alturas, denotadas por $x_1 , x_2 , . . . , x_n$ de uma distribuição normal de média $1,65$ metros e desvio-padrão $0,15$ metros. Em seguida, utilize a relação ($Y_i = α + βx_i + ϵ_i$, para $i = 1, . . . , n$) para gerar uma
amostra de pesos, denotadas aqui por $Y_1, Y_2 , . . . , Y_n$ .

In [ ]:
set.seed(123)
n = 100  # Tamanho da amostra
xB = 1.65  # Média da altura
sd_x = 0.15  # Desvio-padrão da altura

alpha = 60  # Intercepto
beta = 10  # Coeficiente angular
v = 5  # Graus de liberdade da distribuição t
sigma = 5  # Desvio-padrão do erro

# Gerando amostra de alturas a partir de uma distribuição N(1.65; 0.15^2)
x = rnorm(n, xB, sd_x)

# Gerando fatores aleatórios epsilon, e ∼ t_ν(0,σ²)
e = 0 + rt(n, v) * sigma

# Gerando amostra de "pesos" utilizando o modelo de regressão
y = alpha + beta * x + e

y

[1] 72.01864 74.58250 71.92642 65.83357 81.50553 82.06868 79.81554 75.36617
  [9] 79.59960 77.92146 80.34264 81.66194 77.76155 81.06858 84.28239 76.99139
 [17] 55.93720 95.35205 69.21209 70.08673 74.78677 74.62556 73.43499 64.82881
 [25] 68.73688 71.62132 77.66434 95.99835 74.68413 71.61477 74.04970 75.20659
 [33] 71.94840 72.53781 75.37545 82.65187 80.47554 85.99561 85.25000 67.00642
 [41] 97.10803 74.94471 71.81671 79.71192 78.02213 75.76415 71.45121 76.25756
 [49] 79.28897 73.74168 81.84269 74.46633 71.15879 84.83941 75.69204 73.59416
 [57] 78.32161 76.77978 73.11001 76.88859 82.00963 74.35958 70.77187 78.98618
 [65] 83.97094 79.63413 70.84744 84.12921 75.58054 79.93709 76.09951 68.92752
 [73] 81.48687 83.33657 74.31214 82.79644 84.11750 75.53691 78.01579 80.99545
 [81] 81.20892 90.00710 69.00156 84.77519 89.77137 86.80809 65.65208 54.99440
 [89] 77.76002 80.82901 87.15032 76.55817 71.23810 67.17905 65.41887 73.72069
 [97] 82.10814 52.16086 79.46548 79.40390

O Objetivo agora é estimar o vetor de parâmetros ($α, β, σ^2$ ) para $ν$ fixo. Considere, inicialmente, em sua simulação, $n = 100$, $α = −170$, $β = 140$, $σ^2 = 0.15^2$, $ν = 10$ e defina $set.seed(123)$ no R. Depois verifique para outras sementes aleatórias e combinações de tamanho de amostra e vetor de parâmetros.

In [ ]:
set.seed(123)

xB = 1.65  # Média da altura
n = 100
alpha = -170
beta = 140
sigma2 = 0.15^2

v = 10

# Gerando amostra de alturas a partir de uma distribuição N(1.65; 0.15^2)
x = rnorm(n, xB, sqrt(sigma2))

# Gerando fatores aleatórios epsilon, e ∼ t_ν(0,σ²)
e = 0 + rt(n, v) * sqrt(sigma2)

# Gerando amostra de "pesos" utilizando o modelo de regressão
y = alpha + beta * x + e

# Valor inicial e valor máximo de iterações
k = 1
k_max = 50

# Tolerancia de 4 casa decimais
tol = 10^(-4)

# Vetor dos parâmetros
alpha_values = numeric()
beta_values = numeric()
sigma_sq_values = numeric()

# Valores iniciais para alpha, beta e sigma_sq
alpha_values[1] = mean(y)
beta_values[1] = 0
sigma_sq_values[1] = var(y)

while (TRUE) {
  mu_i = alpha_values[k] - beta_values[k] * x

  # Passo E
  d = (y - mu_i )^2 / sigma_sq_values[k]
  si = (v + 1)/(v + d)

  # Passo M
  ## alpha
  alpha_values[k + 1] = sum(y * si) / sum(si)

  ## beta
  beta_values[k + 1] = sum(x * y * si) / sum(x^2 * si)

  ## sigma_sq
  sigma_sq_values[k + 1] = sum(  si*(y - mu_i)^2 )/n

  # Cálculo da tolerância
  tol1 = abs(sigma_sq_values[k + 1] - sigma_sq_values[k])
  tol2 = abs(alpha_values[k + 1] - alpha_values[k])
  tol3 = abs(beta_values[k + 1] - beta_values[k])

  Tolerancia = max(tol1, tol2, tol3)

  # Incrementar k
  k = k + 1

  # Verificando a convergência
  if ((k > k_max) || (Tolerancia < tol)) break
}

In [ ]:
cat("Valores de alpha, beta e sigma^2 obtidos:\n\n")
tabela = cbind(Iterações = seq(1:k),Alpha = alpha_values, Beta = beta_values, Sigma2 = sigma_sq_values)
tabela
cat("Número de iterações:", k, "\n")

Valores de alpha, beta e sigma^2 obtidos:



Iterações Alpha    Beta     Sigma2   
 [1,]  1        62.90962  0.00000  366.6453
 [2,]  2        62.79954 38.35795  318.3444
 [3,]  3        55.65038 35.23035 1844.0625
 [4,]  4        60.47863 37.41291 3974.3387
 [5,]  5        61.61381 37.91929 4483.3183
 [6,]  6        61.74408 37.97728 4525.0865
 [7,]  7        61.75368 37.98154 4526.8145
 [8,]  8        61.75407 37.98172 4526.7680
 [9,]  9        61.75406 37.98171 4526.7511
[10,] 10        61.75406 37.98171 4526.7493
[11,] 11        61.75406 37.98171 4526.7491
[12,] 12        61.75406 37.98171 4526.7491

Número de iterações: 12 


Depois verifique para outras sementes aleatórias e combinações de tamanho de amostra e vetor de parâmetros.

 Agora vamos considera, $n = 1000$, $α = 90$, $β = 30$, $σ^2 = 0.1^2$, $ν = 7$ e defina $set.seed(514096)$ no R.

In [ ]:
set.seed(514096)

xB = 1.5  # Média da altura
n = 1000
alpha = 90
beta = 30
sigma2 = 0.1^2

v = 7

# Gerando amostra de alturas a partir de uma distribuição N(1.65; 0.15^2)
x = rnorm(n, xB, sqrt(sigma2))

# Gerando fatores aleatórios epsilon, e ∼ t_ν(0,σ²)
e = 0 + rt(n, v) * sqrt(sigma2)

# Gerando amostra de "pesos" utilizando o modelo de regressão
y = alpha + beta * x + e

# Valor inicial e valor máximo de iterações
k = 1
k_max = 50

# Tolerancia de 4 casa decimais
tol = 10^(-4)

# Vetor dos parâmetros
alpha_values = numeric()
beta_values = numeric()
sigma_sq_values = numeric()

# Valores iniciais para alpha, beta e sigma_sq
alpha_values[1] = mean(y)
beta_values[1] = 0
sigma_sq_values[1] = var(y)

while (TRUE) {
  mu_i = alpha_values[k] - beta_values[k] * x

  # Passo E
  d = (y - mu_i )^2 / sigma_sq_values[k]
  si = (v + 1)/(v + d)

  # Passo M
  ## alpha
  alpha_values[k + 1] = sum(y * si) / sum(si)

  ## beta
  beta_values[k + 1] = sum(x * y * si) / sum(x^2 * si)

  ## sigma_sq
  sigma_sq_values[k + 1] = sum(  si*(y - mu_i)^2 )/n

  # Cálculo da tolerância
  tol1 = abs(sigma_sq_values[k + 1] - sigma_sq_values[k])
  tol2 = abs(alpha_values[k + 1] - alpha_values[k])
  tol3 = abs(beta_values[k + 1] - beta_values[k])

  Tolerancia = max(tol1, tol2, tol3)

  # Incrementar k
  k = k + 1

  # Verificando a convergência
  if ((k > k_max) || (Tolerancia < tol)) break
}

In [ ]:
cat("Valores de alpha, beta e sigma^2 obtidos:\n\n")
tabela = cbind(Iterações = seq(1:k),Alpha = alpha_values, Beta = beta_values, Sigma2 = sigma_sq_values)
tabela
cat("Número de iterações:", k, "\n")

Valores de alpha, beta e sigma^2 obtidos:



Iterações Alpha    Beta     Sigma2   
 [1,]  1        30.11908  0.00000  65.08585
 [2,]  2        30.12954 20.28117  53.57699
 [3,]  3        26.34484 18.41890 287.73977
 [4,]  4        28.58658 19.55624 747.38534
 [5,]  5        29.36207 19.94663 955.70293
 [6,]  6        29.50162 20.01690 990.14102
 [7,]  7        29.51988 20.02610 994.16339
 [8,]  8        29.52195 20.02713 994.58679
 [9,]  9        29.52216 20.02724 994.62936
[10,] 10        29.52219 20.02725 994.63352
[11,] 11        29.52219 20.02726 994.63392
[12,] 12        29.52219 20.02726 994.63396

Número de iterações: 12 
