# Ciência de Dados para Negócios III - Trabalho 2 - Regressão Ridge

**Aluno**: Antônio Arthur Silva de Lima

**Matrícula**: 508492

**Professor**: Victor Aguiar Evangelista de Farias

**Data**: 26/10/2025

## Implementação dos Algoritmos

In [1]:
# biblioteca
import numpy as np
import random

### Funções de Qualidade do Ajuste

In [2]:
# MSE (Erro Quadrático Médio)
def MSE(y_true, y_predict):
  n = len(y_true)
  SQRes = np.sum((y_true - y_predict)**2)

  mse = SQRes/n

  return mse

In [3]:
# R2
def R2(y_true, y_predict):
  y_bar = np.mean(y_true)

  SQRes = np.sum((y_true - y_predict)**2)
  SQTot = np.sum((y_true - y_bar)**2)

  R_2 = 1 - SQRes/SQTot

  return R_2


In [4]:
# MAPE (Erro Absoluto Percentual Médio)
def mape(y_true, y_predict):
  n = np.shape(y_true)[0]
  s = np.sum(np.abs((y_true - y_predict)/y_true))

  mape = s/n*100

  return mape

### Funções de Ajuste e Predição

In [5]:
# regressão multivariada regularizada
def ridge_regression(X, y, lbd):

  n = np.shape(X)[0] # número de observações
  p = np.shape(X)[1] + 1 # número de variáveis + intercepto

  I = np.eye(p)
  I[0,0] = 0

  ones = np.ones(n)
  X = np.c_[ones, X]

  w = np.linalg.inv(np.transpose(X) @ X + lbd * I) @ np.transpose(X) @ y
  return w

In [6]:
# função para predição
def predict_multivariate(X, w):
  n = np.shape(X)[0]
  ones = np.ones(n)

  X = np.c_[ones, X]

  return X @ w

## Experimento

### Carregando o conjunto de dados

In [7]:
df = np.loadtxt('artificial1d.csv', delimiter=',')
print(df)

[[-1.         -2.08201726]
 [-0.93103448 -1.32698023]
 [-0.86206897 -1.10559772]
 [-0.79310345 -0.87394576]
 [-0.72413793 -0.28502695]
 [-0.65517241 -0.43115252]
 [-0.5862069  -0.79475402]
 [-0.51724138 -0.88606806]
 [-0.44827586 -0.89989978]
 [-0.37931034 -0.86184365]
 [-0.31034483 -0.88805183]
 [-0.24137931 -1.23595129]
 [-0.17241379 -0.71956827]
 [-0.10344828 -0.45202286]
 [-0.03448276  0.09889951]
 [ 0.03448276  0.34896973]
 [ 0.10344828  0.09747797]
 [ 0.17241379  0.70019809]
 [ 0.24137931  1.31051213]
 [ 0.31034483  1.00177576]
 [ 0.37931034  1.00318231]
 [ 0.44827586  1.14910129]
 [ 0.51724138  1.59220607]
 [ 0.5862069   0.60909009]
 [ 0.65517241  0.59441623]
 [ 0.72413793  0.70300732]
 [ 0.79310345  0.82332241]
 [ 0.86206897  1.10646439]
 [ 0.93103448  1.42295695]
 [ 1.          2.30983768]]


### Embaralhando o conjunto de dados

In [8]:
np.random.seed(508492)
np.random.shuffle(df)
print(df)

[[-0.86206897 -1.10559772]
 [ 0.51724138  1.59220607]
 [ 0.72413793  0.70300732]
 [-0.31034483 -0.88805183]
 [ 0.79310345  0.82332241]
 [ 0.31034483  1.00177576]
 [-0.10344828 -0.45202286]
 [-0.37931034 -0.86184365]
 [-0.93103448 -1.32698023]
 [ 0.65517241  0.59441623]
 [-0.44827586 -0.89989978]
 [ 0.93103448  1.42295695]
 [ 0.03448276  0.34896973]
 [ 0.24137931  1.31051213]
 [ 0.5862069   0.60909009]
 [-0.72413793 -0.28502695]
 [-0.79310345 -0.87394576]
 [ 0.17241379  0.70019809]
 [-0.24137931 -1.23595129]
 [-0.65517241 -0.43115252]
 [ 0.37931034  1.00318231]
 [-0.17241379 -0.71956827]
 [-0.5862069  -0.79475402]
 [ 0.10344828  0.09747797]
 [ 0.44827586  1.14910129]
 [ 0.86206897  1.10646439]
 [-0.03448276  0.09889951]
 [-0.51724138 -0.88606806]
 [-1.         -2.08201726]
 [ 1.          2.30983768]]


### Separando as variáveis

In [9]:
X = df[:, 0]
y = df[:, 1]

print(X)
print(y)

[-0.86206897  0.51724138  0.72413793 -0.31034483  0.79310345  0.31034483
 -0.10344828 -0.37931034 -0.93103448  0.65517241 -0.44827586  0.93103448
  0.03448276  0.24137931  0.5862069  -0.72413793 -0.79310345  0.17241379
 -0.24137931 -0.65517241  0.37931034 -0.17241379 -0.5862069   0.10344828
  0.44827586  0.86206897 -0.03448276 -0.51724138 -1.          1.        ]
[-1.10559772  1.59220607  0.70300732 -0.88805183  0.82332241  1.00177576
 -0.45202286 -0.86184365 -1.32698023  0.59441623 -0.89989978  1.42295695
  0.34896973  1.31051213  0.60909009 -0.28502695 -0.87394576  0.70019809
 -1.23595129 -0.43115252  1.00318231 -0.71956827 -0.79475402  0.09747797
  1.14910129  1.10646439  0.09889951 -0.88606806 -2.08201726  2.30983768]


### Criando novas variáveis

In [10]:
X2, X3, X4 = np.power(X, 2), np.power(X, 3), np.power(X, 4)

X = np.c_[X, X2, X3, X4]

print(X)

[[-8.62068966e-01  7.43162901e-01 -6.40657674e-01  5.52291098e-01]
 [ 5.17241379e-01  2.67538644e-01  1.38382057e-01  7.15769263e-02]
 [ 7.24137931e-01  5.24375743e-01  3.79720366e-01  2.74969920e-01]
 [-3.10344828e-01  9.63139120e-02 -2.98905244e-02  9.27636965e-03]
 [ 7.93103448e-01  6.29013080e-01  4.98872442e-01  3.95657454e-01]
 [ 3.10344828e-01  9.63139120e-02  2.98905244e-02  9.27636965e-03]
 [-1.03448276e-01  1.07015458e-02 -1.10705646e-03  1.14523082e-04]
 [-3.79310345e-01  1.43876338e-01 -5.45737833e-02  2.07004005e-02]
 [-9.31034483e-01  8.66825208e-01 -8.07044159e-01  7.51385941e-01]
 [ 6.55172414e-01  4.29250892e-01  2.81233343e-01  1.84256328e-01]
 [-4.48275862e-01  2.00951249e-01 -9.00815942e-02  4.03814043e-02]
 [ 9.31034483e-01  8.66825208e-01  8.07044159e-01  7.51385941e-01]
 [ 3.44827586e-02  1.18906064e-03  4.10020911e-05  1.41386521e-06]
 [ 2.41379310e-01  5.82639715e-02  1.40637172e-02  3.39469037e-03]
 [ 5.86206897e-01  3.43638526e-01  2.01443274e-01  1.18087436e

### Train/Test Split

In [11]:
n = np.shape(X)[0]
i_final = round(n*0.7)

X_train = X[:i_final]
y_train = y[:i_final]
X_test  = X[i_final:]
y_test  = y[i_final:]

print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[-8.62068966e-01  7.43162901e-01 -6.40657674e-01  5.52291098e-01]
 [ 5.17241379e-01  2.67538644e-01  1.38382057e-01  7.15769263e-02]
 [ 7.24137931e-01  5.24375743e-01  3.79720366e-01  2.74969920e-01]
 [-3.10344828e-01  9.63139120e-02 -2.98905244e-02  9.27636965e-03]
 [ 7.93103448e-01  6.29013080e-01  4.98872442e-01  3.95657454e-01]
 [ 3.10344828e-01  9.63139120e-02  2.98905244e-02  9.27636965e-03]
 [-1.03448276e-01  1.07015458e-02 -1.10705646e-03  1.14523082e-04]
 [-3.79310345e-01  1.43876338e-01 -5.45737833e-02  2.07004005e-02]
 [-9.31034483e-01  8.66825208e-01 -8.07044159e-01  7.51385941e-01]
 [ 6.55172414e-01  4.29250892e-01  2.81233343e-01  1.84256328e-01]
 [-4.48275862e-01  2.00951249e-01 -9.00815942e-02  4.03814043e-02]
 [ 9.31034483e-01  8.66825208e-01  8.07044159e-01  7.51385941e-01]
 [ 3.44827586e-02  1.18906064e-03  4.10020911e-05  1.41386521e-06]
 [ 2.41379310e-01  5.82639715e-02  1.40637172e-02  3.39469037e-03]
 [ 5.86206897e-01  3.43638526e-01  2.01443274e-01  1.18087436e

### Ajuste do modelo para $\lambda = 0$

In [12]:
w = ridge_regression(X_train, y_train, 0)
print(w)

[ 0.08692033  2.24369313  0.024529   -1.48500773 -0.14584596]


### Métricas do teste

In [13]:
y_hat_test = predict_multivariate(X_test, w)

mse_test = MSE(y_test, y_hat_test)
r2_test = R2(y_test, y_hat_test)
mape_test = mape(y_test, y_hat_test)

print(mse_test)
print(r2_test)
print(mape_test)

0.49798483257502313
0.6834838407120555
61.25594037142905


### Ajuste com diferentes valores de $\lambda$

In [14]:
ls = [0, 0.001, 0.01, 0.1, 1, 10, 100]

for i in range(len(ls)):
  w = ridge_regression(X_train, y_train, ls[i])

  # métricas de qualidade de ajuste p/ o conjunto de teste
  mse_t = MSE(y_test, predict_multivariate(X_test, w))
  r2_t = R2(y_test, predict_multivariate(X_test, w))
  mape_t = mape(y_test, predict_multivariate(X_test, w))

  print(f'\nAjuste com lambda = {ls[i]}\n')
  print(f'MSE: {mse_t}')
  print(f'R2: {r2_t}')
  print(f'MAPE: {mape_t}')
  print('\n--------------------------------')



Ajuste com lambda = 0

MSE: 0.49798483257502313
R2: 0.6834838407120555
MAPE: 61.25594037142905

--------------------------------

Ajuste com lambda = 0.001

MSE: 0.4963230691059625
R2: 0.6845400475610719
MAPE: 61.178546798958145

--------------------------------

Ajuste com lambda = 0.01

MSE: 0.4820805185128094
R2: 0.6935925269084824
MAPE: 60.50419938565168

--------------------------------

Ajuste com lambda = 0.1

MSE: 0.388326081211851
R2: 0.7531822823981361
MAPE: 55.45494525608072

--------------------------------

Ajuste com lambda = 1

MSE: 0.28975089748081423
R2: 0.8158360752743494
MAPE: 50.06388085456216

--------------------------------

Ajuste com lambda = 10

MSE: 0.6950895797768311
R2: 0.5582052509221973
MAPE: 62.26354786805347

--------------------------------

Ajuste com lambda = 100

MSE: 1.3886745301830474
R2: 0.11736683520715241
MAPE: 76.82400921430906

--------------------------------
